# Generated by Django 3.2.6 on 2021-08-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=11)),
                ('repository', models.URLField(blank=True, null=True)),
                ('is_active', models.SmallIntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
