# Generated by Django 3.2.6 on 2021-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
